### ISSUE TITLE
Default min height for GroupingChooser

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2291]
If the popover had a minHeight set to allow 2-3 grouping rows, I think it would be less jumpy as a user adds and (especially) removes rows.

**Comment by lbwexler** [comment]
This sounds like a great idea.

**Comment by amcclain** [comment]
I've implemented this for desktop - seemed pretty straightforward.  I looked at mobile, but the onsen dialog doesn't appear to take sizing properties, and after a few minutes trying to get it to work nicely with the inner elements I decided to punt for now.

Note that we are currently claiming to support `popoverWidth` on mobile, but I don't believe this has any effect / is supported:

https://github.com/xh/hoist-react/blob/develop/mobile/cmp/grouping/GroupingChooser.js#L91

@TomTirapani if you wouldn't mind looking when you have a chance, would appreciate. Mobile popover would also likely benefit from more stable sizing to keep the controls in the same place when working with a standard number of dims.

I sized for three by default on desktop - mobile might make a different choice to account for it being a modal, but also ensuring it fits nicely on screen.  Perhaps it should just stretch to fill some percentage of the viewport?

**Comment by TomTirapani** [comment]
Taking a look at mobile now.

I will say (just my two cents), I think the experience / appearance is better without the min height, when both controls expand and shrink to fill the number of options. Having empty white space feels a bit broken, as if there's **_supposed_** to be something there but isn't.

**Comment by lbwexler** [comment]
can we split the difference and make it smaller than the 150?  (and I am
sure you already played with these ATM).

It does seem a bit empty in that screenshot.

**Comment by TomTirapani** [comment]
PR for mobile side here: https://github.com/xh/hoist-react/pull/2323

Having actually implemented it on mobile, would like to redact my former complaint - think the min-height works nicely in the dialog context :)

Still not 100% sure about the desktop popover, but like I said, don't feel too strongly either way.

<img width="384" alt="Screenshot 2021-03-03 at 16 14 26" src="https://user-images.githubusercontent.com/3017757/109836073-b9f9c280-7c3b-11eb-8f86-ab7881accb53.png">

**Comment by amcclain** [comment]
Great thanks - will look at the mobile PR now - and agree we have plenty of room there, with the slightly larger dialog looking _less_ awkward IMO than the super-compact one.

Was happy to tweak the desktop default - took it down to 120px / 2 rows in b97bc443ae70ab2f9ac4d134c6a84fb4332ada62 - was on the fence but agree this is better w/most groupings expected to be 1 or 2 level.
